# Generated by Django 3.2 on 2021-04-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('deskripsi', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destinasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('gambar_url', models.URLField(blank=True)),
                ('alamat', models.TextField()),
                ('situs', models.URLField(blank=True)),
                ('telepon', models.CharField(blank=True, max_length=15)),
                ('provinsi_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destinasi.provinsi')),
            ],
        ),
    ]
