# Generated by Django 3.2 on 2021-04-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinasi', '0003_auto_20210420_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinsi',
            name='deskripsi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='provinsi',
            name='nama',
            field=models.CharField(max_length=40),
        ),
    ]
